--@about
--  # XY Pad by Tech Audio
--
--  Bad case of too many FX params and not enough hands? There's a pad for that!
--
--  ### Getting Started
--  1. Make sure ReaImGui is installed (available through ReaPack)
--  2. Run XY Pad - you'll be greeted with some instructions on how to add mappings and configure your experience.
--  3. Add some mappings, and drag the cursor across the pad - eyes wide, watching those param values sing.
--  4. Sit back, close your eyes and ponder the new sonic horizons you've opened up.
--
--  ### Join our community!
--  - [Discord](https://discord.gg/fCnkP9PhTQ)
--@description XY Pad, by Tech Audio
--@link https://techaud.io
--@link https://github.com/TeamAudio
--@link https://discord.gg/fCnkP9PhTQ
--@version 1.1.0
--@category FX
--@author Tech Audio
--@changelog
--  - Added editable response curves for every mapping: click 'Edit curve' on a mapping, then right-click the pad to add a point, drag points with the right button, and Alt + right-click to remove one (endpoints stay pinned to the pad edges; drag them vertically to set the output range)
--  - Added per-mapping curve controls in the Mappings window: use/bypass the curve, visibility (segments and/or points), color, line thickness and point radius
--  - Added a per-project option controlling whether Y-axis curves are transposed for editing
--  - Retired the Min/Max sliders: existing projects migrate their bounds into the curve automatically, so mappings sound exactly the same and the range is now visible and editable as the curve itself
--  - Fixed the pad responding to clicks aimed at overlapping windows (e.g. dragging a slider in the Mappings window no longer moves mapped parameters)
--  - Fixed mappings breaking permanently when their track was deleted mid-session; deleting a track and undoing now recovers the mapping automatically
--@provides
--  [nomain] .
--  [main] XY_Pad/TA_XY Pad.lua
--  [main] XY_Pad/TA_XY Pad Set X.lua
--  [main] XY_Pad/TA_XY Pad Set Y.lua
--  [main] XY_Pad/TA_XY Pad Full Reset.lua
--  [lua] XY_Pad/config.lua
--  [lua] XY_Pad/dkjson.lua
--  [lua] XY_Pad/extstate.lua
--  [lua] XY_Pad/fonts.lua
--  [lua] XY_Pad/help.lua
--  [lua] XY_Pad/imgui_theme.lua
--  [lua] XY_Pad/logging.lua
--  [lua] XY_Pad/mappings.lua
--  [lua] XY_Pad/storage.lua
--  [lua] XY_Pad/theme.lua
--  [lua] XY_Pad/training.lua
--  [lua] XY_Pad/trap.lua
--  [lua] XY_Pad/ui.lua
--  [lua] XY_Pad/widgets.lua

